[Prefix="libsbml::"]
interface BoundingBox {
};

[Prefix="libsbml::"]
interface GraphicalObject {
};

[Prefix="libsbml::"]
interface CompartmentGlyph {
};

[Prefix="libsbml::"]
interface CubicBezier {
};

[Prefix="libsbml::"]
interface GeneralGlyph {
};

[Prefix="libsbml::"]
interface LineSegment {
};

[Prefix="libsbml::"]
interface ReactionGlyph {
};

[Prefix="libsbml::"]
interface SpeciesGlyph {
  BoundingBox getBoundingBox();
  void setBoundingBox(BoundingBox b);

  DOMString getId();
  void setId(DOMString t);
  boolean isSetId();

  DOMString getSpeciesId();
  void setSpeciesId(DOMString t);
  boolean isSetSpeciesId();
};

[Prefix="libsbml::"]
interface Curve {
  CubicBezier createCubicBezier();
  LineSegment createLineSegment();

  unsigned long getNumCurveSegments();
  LineSegment getCurveSegment(unsigned long n);
};

[Prefix="libsbml::"]
interface SpeciesReferenceGlyph {
  BoundingBox getBoundingBox();
  void setBoundingBox(BoundingBox b);

  CubicBezier createCubicBezier();
  LineSegment createLineSegment();

  Curve getCurve();
};

[Prefix="libsbml::"]
interface TextGlyph {
  BoundingBox getBoundingBox();
  void setBoundingBox(BoundingBox b);

  DOMString getText();
  void setText(DOMString t);
  boolean isSetText();
};

[Prefix="libsbml::"]
interface Layout {
  GraphicalObject createAdditionalGraphicalObject();
  CompartmentGlyph createCompartmentGlyph();
  CubicBezier createCubicBezier();
  GeneralGlyph createGeneralGlyph();
  LineSegment createLineSegment();
  ReactionGlyph createReactionGlyph();
  SpeciesGlyph createSpeciesGlyph();
  SpeciesReferenceGlyph createSpeciesReferenceGlyph();
  TextGlyph createTextGlyph();

  unsigned long getNumAdditionalGraphicalObjects();
  unsigned long getNumCompartmentGlyphs();
  unsigned long getNumGeneralGlyphs();
  unsigned long getNumReactionGlyphs();
  unsigned long getNumSpeciesGlyphs();
  unsigned long getNumTextGlyphs();

  GraphicalObject getAdditionalGraphicalObject(unsigned long n);
  CompartmentGlyph getCompartmentGlyph(unsigned long n);
  GeneralGlyph getGeneralGlyph(unsigned long n);
  ReactionGlyph getReactionGlyph(unsigned long n);
  SpeciesGlyph getSpeciesGlyph(unsigned long n);
  TextGlyph getTextGlyph(unsigned long n);

  GraphicalObject removeAdditionalGraphicalObject(unsigned long n);
  CompartmentGlyph removeCompartmentGlyph(unsigned long n);
  ReactionGlyph removeReactionGlyph(unsigned long n);
  SpeciesGlyph removeSpeciesGlyph(unsigned long n);
  SpeciesReferenceGlyph removeSpeciesReferenceGlyph(DOMString id);
  TextGlyph removeTextGlyph(unsigned long n);
};

[Prefix="libsbml::"]
interface LayoutModelPlugin {
  Layout createLayout();

  // NOTE: libSBML signedness is inconsistent here
  long getNumLayouts();
  Layout getLayout(unsigned long n);
};

[Prefix="libsbmljs::"]
interface LayoutCaster {
  void LayoutCaster();
  LayoutModelPlugin castToLayoutPlugin(SBasePlugin p);
};