[Prefix="libsbml::"]
interface GradientBase {
  DOMString getId();
  void setId(DOMString t);
  boolean isSetId();
};

[Prefix="libsbmljs::"]
interface GradientCaster {
  void GradientCaster();
  boolean isLinear(GradientBase p);
  boolean isRadial(GradientBase p);
};

[Prefix="libsbml::"]
interface ColorDefinition {
  DOMString getId();
  void setId(DOMString t);
  boolean isSetId();

  DOMString createValueString(); // NOTE: may leak (returns rvalue)
  boolean setColorValue(DOMString val);
  void setRGBA(unsigned long r, unsigned long g, unsigned long b, unsigned long a);

  void setRed(unsigned long val);
  void setGreen(unsigned long val);
  void setBlue(unsigned long val);
  void setAlpha(unsigned long val);

  unsigned long getRed();
  unsigned long getGreen();
  unsigned long getBlue();
  unsigned long getAlpha();
};

[Prefix="libsbml::"]
interface GlobalRenderInformation {
  DOMString getId();
  void setId(DOMString t);
  boolean isSetId();

  DOMString getName();
  void setName(DOMString t);
  boolean isSetName();

  DOMString getProgramVersion();
  void setProgramVersion(DOMString t);

  DOMString getBackgroundColor();
  void setBackgroundColor(DOMString t);

  unsigned long getNumColorDefinitions();
  ColorDefinition getColorDefinition(unsigned long n);

  unsigned long getNumGradientDefinitions();
  GradientBase getGradientDefinition(unsigned long n);
};

[Prefix="libsbml::"]
interface RenderListOfLayoutsPlugin {
  unsigned long getNumGlobalRenderInformationObjects();
  GlobalRenderInformation getRenderInformation(unsigned long n);
};

[Prefix="libsbml::"]
interface LocalRenderInformation {
  DOMString getId();
  void setId(DOMString t);
  boolean isSetId();

  DOMString getName();
  void setName(DOMString t);
  boolean isSetName();

  DOMString getProgramVersion();
  void setProgramVersion(DOMString t);

  DOMString getBackgroundColor();
  void setBackgroundColor(DOMString t);

  unsigned long getNumColorDefinitions();
  ColorDefinition getColorDefinition(unsigned long n);

  unsigned long getNumGradientDefinitions();
  GradientBase getGradientDefinition(unsigned long n);
};

[Prefix="libsbml::"]
interface RenderLayoutPlugin {
  unsigned long getNumLocalRenderInformationObjects();
  LocalRenderInformation getRenderInformation(unsigned long n);
};

[Prefix="libsbmljs::"]
interface RenderCaster {
  void RenderCaster();
  RenderListOfLayoutsPlugin castToRenderListOfLayoutsPlugin(SBasePlugin p);
  RenderLayoutPlugin castToRenderLayoutPlugin(SBasePlugin p);
};
