[Prefix="libsbml::"]
interface SpeciesReference {
  DOMString getId();
  DOMString getSpecies();
};

[Prefix="libsbml::"]
interface Reaction {
  DOMString getId();

  long getNumReactants();
  long getNumModifiers();
  long getNumProducts();

  SpeciesReference getReactant(long i);
  SpeciesReference getProduct(long i);
};

[Prefix="libsbml::"]
interface Model {
  long getNumReactions();
  Reaction getReaction(long i);
};

[Prefix="libsbml::"]
interface SBMLDocument {
  long getNumErrors();
  Model getModel();
};

[Prefix="libsbml::"]
interface SBMLReader {
  void SBMLReader();
  SBMLDocument readSBMLFromString(DOMString sbmlstr);
};
